ALTER TABLE "Servico" 
    ALTER COLUMN "nome_oficial" SET NOT NULL,
    ALTER COLUMN "id_municipio" SET NOT NULL,
    ALTER COLUMN "id_tipo" SET NOT NULL;


ALTER TABLE "Tipo_Servico"
    ALTER COLUMN "nome_tipo" SET NOT NULL;


ALTER TABLE "Reserva_Item"
    ADD CONSTRAINT "chk_lucro_positivo" CHECK ("preco_venda" >= "custo_fornecedor"),
    ADD CONSTRAINT "chk_preco_venda_positivo" CHECK ("preco_venda" >= 0),
    ADD CONSTRAINT "chk_custo_fornecedor_positivo" CHECK ("custo_fornecedor" >= 0);

ALTER TABLE "Reserva"
    ADD CONSTRAINT "chk_preco_totoal_positivo"
    CHECK ("preco_total" >= 0); 

ALTER TABLE "Pagamento"
    ADD CONSTRAINT "chk_valor_positivo" 
    CHECK ("valor" >= 0);


ALTER TABLE "Pagamento"
    ALTER COLUMN "id_reserva" SET NOT NULL;


ALTER TABLE "Pagamento" 
    ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY;



-- Indices importantes de acordo com as consultas mais frequentes

CREATE INDEX idx_pagamento_id_reserva ON "Pagamento" ("id_reserva");
CREATE INDEX idx_reserva_id_cliente ON "Reserva" ("id_cliente");
CREATE INDEX idx_itinerario_reserva ON "Itinerario" ("id_reserva");
CREATE INDEX idx_itinerario_status ON "Itinerario" ("status");
CREATE INDEX idx_servico_municipio ON "Servico" ("id_municipio");
CREATE INDEX idx_servico_tipo ON "Servico" ("id_tipo");
CREATE INDEX idx_reserva_item_reserva ON "Reserva_Item" ("id_reserva");
CREATE INDEX idx_fornecedor_servico_pessoa ON "Fornecedor_Servico" ("id_pessoa");


-- Tabela de Auditoria genérica

CREATE TABLE "Log_Auditoria" (
  "id" BIGSERIAL PRIMARY KEY,
  "nome_tabela" VARCHAR(100) NOT NULL,
  "operacao" CHAR(6) NOT NULL CHECK ("operacao" IN ('INSERT', 'UPDATE', 'DELETE')),
  "dados_antigos" JSONB,
  "dados_novos" JSONB,
  "usuario_db" VARCHAR(100) DEFAULT CURRENT_USER,
  -- "usuario_sistema_id" INT, 
  "data_hora" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX "idx_log_auditoria_tabela" ON "Log_Auditoria" ("nome_tabela");
CREATE INDEX "idx_log_auditoria_data" ON "Log_Auditoria" ("data_hora");
CREATE INDEX "idx_log_auditoria_dados_novos" ON "Log_Auditoria" USING gin ("dados_novos");


CREATE OR REPLACE FUNCTION fn_log_auditoria()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'DELETE') THEN
        INSERT INTO "Log_Auditoria" ("nome_tabela", "operacao", "dados_antigos")
        VALUES (TG_TABLE_NAME, 'DELETE', to_jsonb(OLD));
        RETURN OLD;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO "Log_Auditoria" ("nome_tabela", "operacao", "dados_antigos", "dados_novos")
        VALUES (TG_TABLE_NAME, 'UPDATE', to_jsonb(OLD), to_jsonb(NEW));
        RETURN NEW;
    ELSIF (TG_OP = 'INSERT') THEN
        INSERT INTO "Log_Auditoria" ("nome_tabela", "operacao", "dados_novos")
        VALUES (TG_TABLE_NAME, 'INSERT', to_jsonb(NEW));
        RETURN NEW;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;


CREATE TRIGGER trg_auditoria_reserva
AFTER INSERT OR UPDATE OR DELETE ON "Reserva"
FOR EACH ROW EXECUTE FUNCTION fn_log_auditoria();