INSERT INTO "Servico" (
    "id_municipio",
    "nome_oficial",
    "id_tipo",
    "status"
)
VALUES
    (1, 'Hotel Rio do Rastro', 5, 'ATIVO'),
    (1, 'Hotel Rio Rocinha', 5, 'ATIVO'),
    (1, 'Hotelaria Casa do Felipe', 5, 'ATIVO'),
    (1, 'Hostel Rio da vaca', 5, 'ATIVO'),
    (1, 'Hotel morro da palha', 5, 'ATIVO'),
    (2, 'Hotel Receba', 5, 'ATIVO'),
    (1, 'Hotel Trivago', 5, 'ATIVO'),
    (5, 'hotel Mariana', 5, 'ATIVO'),
    (4, 'Hotel Leeroy Jenkins', 5, 'ATIVO'),
    (3, 'Hotel Wano', 5, 'ATIVO'),
    (2, 'Joseph Joestar Companhias aereas', 4, 'ATIVO'),
    (1, 'Bom Voo Companhias aereas', 4, 'ATIVO'),
    (1, 'Paranagua Companhias aereas', 4, 'ATIVO'),
    (3, 'Seriguela Companhias aereas', 4, 'ATIVO'),
    (3, 'Opamecano Companhias aereas', 4, 'ATIVO'),
    (4, 'Vá Rápido Translados', 4, 'ATIVO'),
    (2, 'Auto Locadora Roda Presa', 4, 'ATIVO'),
    (5, 'SafeTrip Seguros de Viagem', 6, 'ATIVO'),
    (1, 'Money Câmbio e Moedas', 6, 'ATIVO'),
    (3, 'Guias Nativos da Região', 6, 'ATIVO'),
    (1, 'Lounge VIP Relax Aeroporto', 6, 'ATIVO'),
    (4, 'Visto Sem Estresse Assessoria', 6, 'ATIVO'),
    (2, 'Mundo Conectado Telecom', 6, 'ATIVO'),
    (5, 'SafeBox Guarda-Volumes', 6, 'ATIVO'),
    (3, 'Brisa do Mar Locadora de Barcos', 6, 'ATIVO'),
    (1, 'Mirante da Serra do Rio do Rastro', 1, 'ATIVO'),
    (2, 'Forte de Copacabana', 2, 'ATIVO'),
    (3, 'Parque das Esculturas', 2, 'ATIVO'),
    (4, 'Parque das Aves', 2, 'ATIVO'),
    (5, 'Museu Zoroastro Artiaga', 2, 'ATIVO'),
    (1, 'Churrascaria Tropeiro', 7, 'ATIVO'),
    (1, 'Café da Montanha', 7, 'ATIVO'),
    (1, 'Bistrô Lauro Müller', 7, 'ATIVO'),
    (1, 'Pizzaria da Serra', 7, 'ATIVO'),
    (2, 'Churrascaria Palace', 7, 'ATIVO'),
    (2, 'Boteco Belmonte Copacabana', 7, 'ATIVO'),
    (2, 'La Trattoria', 7, 'ATIVO'),
    (2, 'Restaurante Cervantes', 7, 'ATIVO'),
    (3, 'Parraxaxá', 7, 'ATIVO'),
    (3, 'Restaurante Leite', 7, 'ATIVO'),
    (3, 'Seu Boteco Marco Zero', 7, 'ATIVO'),
    (3, 'Bistrô do Cais', 7, 'ATIVO'),
    (4, 'Restaurante Porto Canoas', 7, 'ATIVO'),
    (4, 'Rafain Churrascaria Show', 7, 'ATIVO'),
    (4, 'Cabeça de Boi', 7, 'ATIVO'),
    (4, 'Churrascaria do Gaúcho', 7, 'ATIVO'),
    (5, 'Chão Nativo', 7, 'ATIVO'),
    (5, 'Restaurante Piquiras', 7, 'ATIVO'),
    (5, 'Carne de Sol 1008', 7, 'ATIVO'),
    (5, 'Panelinha Grill', 7, 'ATIVO');